In [12]:
!pip install pandas
!pip install numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in c:\users\asus\bank_marketing\venv\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\bank_marketing\venv\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\bank_marketing\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\bank_marketing\venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\bank_marketing\venv\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\asus\bank_marketing\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in c:\users\asus\bank_marketing\venv\lib\site-packages (2.1.1)

In [15]:
import pandas as pd
import numpy as np

In [16]:
marketing = pd.read_csv("bank_marketing.csv")

In [17]:
marketing.head(-5)

,client_id,age,job,marital,education,credit_default,mortgage,month,day,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome
0,0,56,housemaid,married,basic.4y,no,no,may,13,261,1,0,nonexistent,93.994,4.857,no
1,1,57,services,married,high.school,unknown,no,may,19,149,1,0,nonexistent,93.994,4.857,no
2,2,37,services,married,high.school,no,yes,may,23,226,1,0,nonexistent,93.994,4.857,no
3,3,40,admin.,married,basic.6y,no,no,may,27,151,1,0,nonexistent,93.994,4.857,no
4,4,56,services,married,high.school,no,no,may,3,307,1,0,nonexistent,93.994,4.857,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41178,41178,62,retired,married,university.degree,no,no,nov,26,483,2,3,success,94.767,1.031,yes
41179,41179,64,retired,divorced,professional.course,no,yes,nov,7,151,3,0,nonexistent,94.767,1.028,no
41180,41180,36,admin.,married,university.degree,no,no,nov,27,254,2,0,nonexistent,94.767,1.028,no
41181,41181,37,admin.,married,university.degree,no,yes,nov,20,281,1,0,nonexistent,94.767,1.028,yes
41182,41182,29,unemployed,single,basic.4y,no,yes,nov,26,112,1,1,success,94.767,1.028,no

In [18]:
# Split into the three tables
client = marketing[["client_id", "age", "job", "marital", "education", "credit_default", "mortgage"]]
campaign = marketing[["client_id", "number_contacts", "month", "day", "contact_duration", "previous_campaign_contacts", "previous_outcome", "campaign_outcome"]]
economics = marketing[["client_id", "cons_price_idx", "euribor_three_months"]]

In [22]:
## Editing the client dataset
# Clean education column
client["education"] = client["education"].str.replace(".", "_")
client["education"] = client["education"].replace("unknown", np.nan)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\1972858270.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  client["education"] = client["education"].str.replace(".", "_")
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\1972858270.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  client["education"] = client["education"].replace("unknown", np.nan)

In [23]:
# Clean job column
client["job"] = client["job"].str.replace(".", "_")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\60804052.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  client["job"] = client["job"].str.replace(".", "_")

In [24]:
# Clean and convert client columns to bool data type
for col in ["credit_default", "mortgage"]:
    client[col] = client[col].map({"yes":1,
                                  "no":0,
                                  "unknown":0})
    client[col] = client[col].astype(bool)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3382103761.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  client[col] = client[col].map({"yes":1,
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3382103761.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  client[col] = client[col].astype(bool)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3382103761.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  client[col] = client[col].map({"yes":1,
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3382103761.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  client[col] = client[col].astype(bool)

In [26]:
# Editing the campaign dataset
# Change campaign_outcome to binary values
campaign["campaign_outcome"] = campaign["campaign_outcome"].map({"yes":1,
                                                                 "no":0})

# Convert previous_outcome to binary values
campaign["previous_outcome"] = campaign["previous_outcome"].map({"success":1,
                                                                "failure": 0,
                                                                "nonexistent": 0})

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3167900489.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  campaign["campaign_outcome"] = campaign["campaign_outcome"].map({"yes":1,
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3167900489.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  campaign["previous_outcome"] = campaign["previous_outcome"].map({"success":1,

In [29]:
# Add year column
campaign["year"] = "2022"

# Convert day to string
campaign["day"] = campaign["day"].astype(str)

# Add last_contact_date column
campaign["last_contact_date"] = campaign["year"] + "-" + campaign["month"] + "-" + campaign["day"]

# Convert to datetime
campaign["last_contact_date"] = pd.to_datetime(campaign["last_contact_date"],format="%Y-%b-%d")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3861400407.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  campaign["year"] = "2022"
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3861400407.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  campaign["day"] = campaign["day"].astype(str)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3861400407.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  campaign["last_contact_date"] = campaign["year"] + "-" + campaign["month"] + "-" + campaign["day"]
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\3861400407.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  campaign["last_contact_date"] = pd.to_datetime(campaign["last_contact_date"],format="%Y-%b-%d")

In [30]:
# Clean and convert outcome columns to bool
for col in ["campaign_outcome", "previous_outcome"]:
  campaign[col] = campaign[col].astype(bool)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\2044194194.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  campaign[col] = campaign[col].astype(bool)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_8372\2044194194.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  campaign[col] = campaign[col].astype(bool)